<section class="relative"><div id="67dfcb9afedc41b512bd1510" class="relative flex flex-none flex-shrink-0 break-word items-center fix-safari-flickering" style="min-height: calc(-128px); z-index: 39; scroll-margin-top: calc(174px + 4rem); padding-top: 0px; padding-bottom: 0px;"><div class="absolute inset-0 z-10 pointer-events-none"><div class="absolute inset-0 z-10" style="background-color: rgb(255, 255, 255);"></div></div><div class="relative z-10 container mx-auto pt-8 lg:pt-12 pb-8 lg:pb-12"><div><div class="absolute left-0 top-8 min-h-full min-w-full"></div><div class="transition-all transition-all ease-in-out duration-500  opacity-100 translate-y-0 flex flex-col gap-4 mb-6 items-center text-center mx-auto"><h1 class="break-word heading-large block w-full mx-auto" style="color: rgb(17, 24, 39);">Aktuellt</h1></div><div class="flex flex-wrap relative justify-center" style="gap: 40px;"><div class="group w-full relative overflow-hidden" style="flex: 0 0 calc(100% + 0px);"><div class="absolute left-0 top-8 min-h-full min-w-full"></div><div class="transition-all transition-all ease-in-out duration-500 delay-100 opacity-100 translate-y-0 h-full"><div class="flex flex-col h-full"><div><div class="flex-shrink-0 relative overflow-hidden aspect-w-16 aspect-h-9"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:absolute;top:0;left:0;bottom:0;right:0"><img alt="" title="" src="<?php echo NOAV_URI; ?>/img/24ruF0q8uHnG5K43p1mXL8wNPpXtSpmqiZvJcAPOHBVKMTQr0i2ud0mfcaNv5vTa.jpg" class="" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:contain;object-position:50% 95%"></span></div><div class="flex flex-row items-center justify-center"></div><div class="flex flex-col"><div class="flex flex-col items-center text-center mx-auto py-6" style="color: rgb(17, 24, 39);"><div class="rich-text-block mx-auto" style="color:currentColor"><p style="text-align: center;"><strong>Vinkelviken önskar er en härlig sommar!</strong><br>____________________________________</p>
<p style="text-align: center;">Vi har två mässor att se framemot under våren och vi hoppas att vi ses där.</p>
<p style="text-align: center;">23 april Lund Scandic Star Hotel<br>28 maj Skövde Kulturhus<br><strong><em>____________________________________</em></strong></p>
<p style="text-align: center;"><em>251224</em><strong><br>God jul och gott nytt år!<br>____________________________________</strong></p>
<p style="text-align: center;"><strong>HVB-dagen i Växjö<br></strong></p>
<p>På torsdag den 13 november ställer vi ut på HVB-dagen i Växjö.<br>Kom fram och hälsa. Ni hittar oss på Växjö Konserthus!<br><strong>____________________________________</strong></p>
<p style="text-align: center;"><em>251031</em><strong><br></strong>Vinkelviken önskar glad Halloween!<strong><br>____________________________________</strong></p>
<p>Torsdag den 30 oktober utbildas personalgruppen i taktisk kommunikation och självskydd av SäkerhetsAkademien.<br><strong>____________________________________</strong></p>
<p><strong>HVB-dagen i Malmö</strong><br>På torsdag den 23 oktober ställer vi ut på HVB-dagen i Malmö.</p>
<p>Välkommen till vår monter på Scandic Triangeln.<br><strong>____________________________________</strong></p>
<p><strong>HVB-dagen i Skövde</strong><br>Den 15 maj ställer vi ut på HVB-dagen i Skövde.</p>
<p>Välkommen till vår monter på Skövde Kulturhus!<br><strong>____________________________________</strong></p>
<p><strong>FIT- Feedback informed treatment</strong><br>På torsdag den 24 april har personalgruppen återigen Niklas Waitong på besök för att fortsätta med FIT-utbildningen.<br>____________________________________<strong><br><br>HVB-dagen i Lund</strong> <br>Den 3 april ställer vi ut på HVB-dagen i Lund, <br>Scandic Hotel.</p>
<p class="normal">Välkommen till vår monter!<br>_____________________________________</p>
<p class="normal" style="text-align: center;"><strong>FIT - Feedback informed treatment</strong><br>Den 27 mars utbildas hela vår personalgrupp i FIT. Utbildare Niklas Waitong kommer till vår verksamhet.<br><strong><em>_________________________________</em></strong></p>
<p style="text-align: center;"><em>250222</em><br>Ytterligare nyheter är att vi kommer delta på HVB-dagarna, Stockholm 11 mars och Lund 3 april. Kom och träffa oss.<br><strong><em>__________________________________</em></strong></p>
<p style="text-align: center;"><em>250122<br></em>Personalen på Vinkelviken kommer under våren genomgå utbildning i FIT och rePULSE.<br><strong>__________________________________</strong></p>
<p style="text-align: center;"><em>250108</em><br>Vi har mycket spännande att se framemot år 2025. Håll utkik på vår hemsida för mer information :)<br><em><strong>__________________________________</strong></em></p>
<p style="text-align: center;"><em>241224</em><br>Vinkelviken vill önska er alla en riktigt god jul och gott nytt år, fyllt av glädje och kärlek!<br><em><strong>___________________________________</strong></em></p>
<p style="text-align: center;"><em>241202</em><br>Vi har sedan december 2024 inlett ett samarbete med Ringsjöortens ryttarförening där möjligheten till fritidsaktivitet, praktik och ridskola finns. Vi har även inlett samarbete med olika butiker i närområdet för att ungdomarna ska kunna göra praktik.<br><em><strong>__________________________________</strong></em></p>
<p style="text-align: center;"><em>241105</em><br>Sedan den 5 november har vi öppnat dörrarna till vår nya verksamhet Vinkelvikens HVB.</p></div></div></div></div></div></div></div></div></div></div><svg class="absolute bottom-0 left-0" width="0" height="0" viewBox="0 0 0 0"><clipPath id="67dfcb9afedc41b512bd1510-slantLeft"><rect width="0" height="0" fill="transparent"></rect><path d="M0 0L-0 0V0H0" transform="translate(0, 0)" fill="transparent"></path></clipPath></svg></div></section>
