<section class="relative"><div id="65e62a9c08743520858cbd4c" class="flex flex-none flex-shrink-0 relative break-word items-center fix-safari-flickering" style="min-height: calc(-128px); z-index: 39; padding-top: 0px; padding-bottom: 0px;"><div class="absolute inset-0 z-10 pointer-events-none"><div class="absolute inset-0 z-10" style="background-image: linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255));"></div></div><div class="relative z-10 container mx-auto pt-8 lg:pt-12 pb-8 lg:pb-12"><div class="absolute left-0 top-8 min-h-full min-w-full"></div><div class="transition-all transition-all ease-in-out duration-500  opacity-100 translate-y-0 flex w-full gap-10 lg:gap-20 flex-col lg:flex-row items-start"><div class="flex-1 flex flex-col max-w-240 items-start"><div class="rich-text-block" style="color: rgb(17, 24, 39);"><h3 style="text-align:left">Behandling och metoder</h3>
<p style="text-align:left">Vi arbetar strukturerat med individuella lösningar utifrån socialtjänstens uppdrag. Vi lägger stor vikt vid tydlighet, förutsägbarhet och trygghet.</p>
<p style="text-align:left">Vi arbetar lågaffektivt och kravanpassat. Vi vet att goda relationer och delaktighet är viktigt för att möjliggöra förändring. </p>
<p style="text-align:left">Vi erbjuder färdighetsträning både enskilt och i grupp.</p>
<p style="text-align:left">Vi arbetar KBT-inriktat med evidensbaserade metoder - rePulse/reManga och ART.</p>
<p style="text-align:left">Vår personal är utbildade i bland annat rePulse, ART, ÅP (Återfallsprevention), Connect, FIT (Feedback informed treatment), MI (Motiverande samtal), TMO (traumamedveten omsorg) samt Lågaffektivt bemötande.</p>
<p style="text-align:left"><strong>Psykolog i verksamheten</strong><br>Vi samarbetar med BUS-mottagningen, psykolog Johan Nordahl. Samtal erbjuds inom ramen för placeringen och kan komma igång snabbt. Psykolog och behandlare arbetar i team runt ungdomen.</p>
<p style="text-align:left"><strong>NPF-utredning</strong><br>Vi samarbetar med psykolog Marie Kleiman Ring på MKR psykologtjänst i Skåne. Snabb och gedigen utredning vid behov.</p>
<p style="text-align:left"><strong>Sjuksköterska</strong><br>Sjuksköterska Pia Lönquist arbetar i vår verksamhet på deltid. Pia har lång erfarenhet av arbete inom barn- och ungdomspsykiatrin, men även inom vuxenpsykiatri och somatisk vård.</p>
<p style="text-align:left"><strong>Familjesamtal</strong><br>Vinkelviken vill ha nära kontakt med vårdnadshavare och nätverk under placeringstiden. Vi erbjuder familjestöd/samtal och finns tillgängliga när ungdomen har umgänge.&nbsp;</p>
<p style="text-align:left"><strong>Skola eller daglig sysselsättning</strong><br>Skola eller annan daglig sysselsättning är viktigt hos oss. Vi samarbetar med skolor i kommunen men även med skolor i andra kommuner och med privata alternativ. Vi erbjuder läxhjälp.</p>
<p style="text-align:left">Verksamheten erbjuder anpassade aktiviteter måndag till fredag för att sysselsätta och förbereda ungdomen för vuxenlivet. Aktiviteterna planeras och utförs utifrån ungdomens behov.&nbsp;</p>
<p style="text-align:left"><strong>Fritid</strong><br>Vi erbjuder och motiverar till en aktiv fritid. Vi har nära till natur och en dag i veckan är avsatt för friluftsliv.</p>
<p style="text-align:left">Vi samarbetar med Ringsjöortens ryttarförening där möjligheten till fritidsaktivitet, praktik och ridskola finns.</p>
<p style="text-align:left"><strong>Samverkan med lokal polis</strong><br>Vinkelviken har fått en kontaktperson hos polisen för att få till en närmare samverkan och förenkla kontaktvägen kring brottsförebyggande frågor med HVB-hem. Kontaktperson hos polisen kan besöka vårt HVB, träffa ungdomar, bygga relationer och skapa förtroende, samt ta emot tips och rådgöra personal</p>
<p style="text-align:left"><strong>Utsluss/eftervård<br></strong>I samråd med placerande kommun stöttar vi ungdomen i planering om hemflytt eller utsluss till stödboende.</p></div></div><div class="flex-1 flex w-full h-full justify-center lg:justify-start"><div class="flex-shrink-0 relative w-full h-full mx-auto aspect-w-16 aspect-h-9"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:absolute;top:0;left:0;bottom:0;right:0"><img alt="" title="" src="<?php echo NOAV_URI; ?>/img/26jvjrbn14m6BVGP5KMtCnaqC4l0KI0y4hHSBTfAdk0TorvLiIgQjV7TNKj4Ve5H.jpg" class="rounded-2xl md:rounded-3xl lg:rounded-4xl" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover;object-position:45% 70%"></span></div></div></div></div><svg class="absolute bottom-0 left-0" width="0" height="0" viewBox="0 0 0 0"><clipPath id="65e62a9c08743520858cbd4c-slantLeft"><rect width="0" height="0" fill="transparent"></rect><path d="M0 0L-0 0V0H0" transform="translate(0, 0)" fill="transparent"></path></clipPath></svg></div></section>
